// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0
// source: protos/Example/example.proto

package github_com

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExampleGreeting_SayHelloExample_FullMethodName = "/Example.ExampleGreeting/SayHelloExample"
)

// ExampleGreetingClient is the client API for ExampleGreeting service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExampleGreetingClient interface {
	SayHelloExample(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type exampleGreetingClient struct {
	cc grpc.ClientConnInterface
}

func NewExampleGreetingClient(cc grpc.ClientConnInterface) ExampleGreetingClient {
	return &exampleGreetingClient{cc}
}

func (c *exampleGreetingClient) SayHelloExample(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, ExampleGreeting_SayHelloExample_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExampleGreetingServer is the server API for ExampleGreeting service.
// All implementations must embed UnimplementedExampleGreetingServer
// for forward compatibility.
type ExampleGreetingServer interface {
	SayHelloExample(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedExampleGreetingServer()
}

// UnimplementedExampleGreetingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExampleGreetingServer struct{}

func (UnimplementedExampleGreetingServer) SayHelloExample(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SayHelloExample not implemented")
}
func (UnimplementedExampleGreetingServer) mustEmbedUnimplementedExampleGreetingServer() {}
func (UnimplementedExampleGreetingServer) testEmbeddedByValue()                         {}

// UnsafeExampleGreetingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExampleGreetingServer will
// result in compilation errors.
type UnsafeExampleGreetingServer interface {
	mustEmbedUnimplementedExampleGreetingServer()
}

func RegisterExampleGreetingServer(s grpc.ServiceRegistrar, srv ExampleGreetingServer) {
	// If the following call panics, it indicates UnimplementedExampleGreetingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExampleGreeting_ServiceDesc, srv)
}

func _ExampleGreeting_SayHelloExample_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleGreetingServer).SayHelloExample(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExampleGreeting_SayHelloExample_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleGreetingServer).SayHelloExample(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExampleGreeting_ServiceDesc is the grpc.ServiceDesc for ExampleGreeting service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExampleGreeting_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Example.ExampleGreeting",
	HandlerType: (*ExampleGreetingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHelloExample",
			Handler:    _ExampleGreeting_SayHelloExample_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/Example/example.proto",
}
