// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.9
// source: protos/Shadow/shadow.proto

package github_com

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Shadow_SayShadow_FullMethodName = "/Shadow.Shadow/SayShadow"
)

// ShadowClient is the client API for Shadow service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShadowClient interface {
	SayShadow(ctx context.Context, in *HelloShadow, opts ...grpc.CallOption) (*ReplyShadow, error)
}

type shadowClient struct {
	cc grpc.ClientConnInterface
}

func NewShadowClient(cc grpc.ClientConnInterface) ShadowClient {
	return &shadowClient{cc}
}

func (c *shadowClient) SayShadow(ctx context.Context, in *HelloShadow, opts ...grpc.CallOption) (*ReplyShadow, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplyShadow)
	err := c.cc.Invoke(ctx, Shadow_SayShadow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShadowServer is the server API for Shadow service.
// All implementations must embed UnimplementedShadowServer
// for forward compatibility.
type ShadowServer interface {
	SayShadow(context.Context, *HelloShadow) (*ReplyShadow, error)
	mustEmbedUnimplementedShadowServer()
}

// UnimplementedShadowServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShadowServer struct{}

func (UnimplementedShadowServer) SayShadow(context.Context, *HelloShadow) (*ReplyShadow, error) {
	return nil, status.Error(codes.Unimplemented, "method SayShadow not implemented")
}
func (UnimplementedShadowServer) mustEmbedUnimplementedShadowServer() {}
func (UnimplementedShadowServer) testEmbeddedByValue()                {}

// UnsafeShadowServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShadowServer will
// result in compilation errors.
type UnsafeShadowServer interface {
	mustEmbedUnimplementedShadowServer()
}

func RegisterShadowServer(s grpc.ServiceRegistrar, srv ShadowServer) {
	// If the following call panics, it indicates UnimplementedShadowServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Shadow_ServiceDesc, srv)
}

func _Shadow_SayShadow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloShadow)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShadowServer).SayShadow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Shadow_SayShadow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShadowServer).SayShadow(ctx, req.(*HelloShadow))
	}
	return interceptor(ctx, in, info, handler)
}

// Shadow_ServiceDesc is the grpc.ServiceDesc for Shadow service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Shadow_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Shadow.Shadow",
	HandlerType: (*ShadowServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayShadow",
			Handler:    _Shadow_SayShadow_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/Shadow/shadow.proto",
}
